[workspace]
members = [
    "obfuscator",
    "my_lib",
]

[package]
name = "my_project"
version = "0.1.0"
edition = "2021"

[dependencies]
obfuscator = { path = "./obfuscator" }
my_lib = { path = "./my_lib" }
