[package]
name = "tulpar"
version = "0.1.0"
edition = "2021"

[dependencies]
obfuscator = { path = "obfuscator" }
zeroize = "1.8.2"
crc32fast = "1.5.0"
base91 = "0.1.0"
base122-rs = "0.1.4"
base36 = "0.0.1"
walkdir = "2.3"
quote = "1.0"
syn = { version = "2.0", features = ["full", "fold", "visit-mut", "visit"] }
rand = "0.9"
base45 = "3.1.0"
base32 = "0.5.1"
base64 = "0.22.1"
base85 = "2.0.0"
bs58 = "0.5.1"
proc-macro2 = "1.0"
regex = "1.10"
aes = "0.8.4"
hex = "0.4.3"
getrandom = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.21.3"
windows = { version = "0.56.0", features = [
    "Win32_System_Com",
    "Win32_System_TaskScheduler",
    "Win32_System_Ole",
    "Win32_Security",
    "Win32_Foundation",
    "Win32_System_SystemInformation",
    "Win32_System_Variant",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_Storage_FileSystem",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Registry", # Kept for refactoring even though registry logic will be removed
] }

[profile.release]
opt-level = 3
lto = true
