[package]
name = "files_to_telegram"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "0.6"
dirs = "4.0"
reqwest = { version = "0.11", features = ["multipart", "json"] }
tokio = { version = "1.0", features = ["full"] }
rand = "0.8"
base64 = "0.22.1"

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "z"
strip = true
